"""Initial migration with all tables

Revision ID: 7e2a709542ff
Revises: 
Create Date: 2026-01-06 21:30:26.794585
"""
from alembic import op
import sqlalchemy as sa


revision = '7e2a709542ff'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devocionales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('BASICO', 'PREMIUM', 'PREMIUM_ANUAL', name='tipoplan'), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('devocional_id', sa.UUID(), nullable=False),
    sa.Column('fecha_agregado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['devocional_id'], ['devocionales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'devocional_id', name='unique_user_devocional_favorito')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('mp_payment_id', sa.String(), nullable=True),
    sa.Column('mp_preference_id', sa.String(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'CANCELADO', name='estadopago'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_lectura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('devocional_id', sa.UUID(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('tiempo_lectura_segundos', sa.Integer(), nullable=True),
    sa.Column('video_visto', sa.Boolean(), nullable=True),
    sa.Column('progreso_video_segundos', sa.Integer(), nullable=True),
    sa.Column('ultima_visita', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['devocional_id'], ['devocionales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'devocional_id', name='unique_user_devocional_progreso')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscriptions')
    op.drop_table('progreso_lectura')
    op.drop_table('pagos')
    op.drop_table('favoritos')
    op.drop_table('users')
    op.drop_table('planes')
    op.drop_table('devocionales')
    # ### end Alembic commands ###
